dist: trusty
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
stages:
  - build
  - test

cache:
  directories:
  - bin

jobs:
  include:
    -
      stage: build
      script:
        - 'export CC=gcc-7'
        - 'export CXX=g++-7'
        - 'cmake CMakeLists.txt'
        - make
    -
      stage: test
      script: ./bin/cpp_decorators_tests
